---
box:
provider:

credentials:

vm:
  name:
  description:
  hotplug:
  cpu:
  ram:

private_network:
  enable:
  name:
  ip:

synced_folders:

mindsdb:
  version:
  apis:

guest_system:
  skip_python_alias:
  pip_version:
  on_login:
  swappiness:

include:
  clients:
    mariadb:
    mycli:
