#!/bin/sh

COLOR_GREEN='\033[1;32m'
COLOR_BLUE='\033[0;36m'
COLOR_DEFAULT='\033[0m'

echo "$COLOR_GREEN
  +------------------------+
  |                        |
  |  MindsDB box           |
  |                        |
  |░░░░░░░░░░░░░░░░░░░░░░░░|
  |                        |
  |      by Vettabase      |
  |                        |
  |    vettabase.com       |
  |    info@vettabase.com  |
  |                        |
  +------------------------+
$COLOR_DEFAULT

* Contribute this Vagrant box:
  https://github.com/Vettabase/vagrant-mindsdb

* For support requests regarding MindsDB itself:
  https://mindsdb.com

* MindsDB Community:
  https://community.mindsdb.com

Vettabase offers support and consulting regarding
MindsDB integration with existing systems/databases,
MindsDB on-premise deployment & automation,
and several database systems.

Vettabase consulting services: $COLOR_BLUE
https://vettabase.com/blog/services$COLOR_DEFAULT
"
